[build]
  publish = "dist/"
  command = "npm run build"

[build.environment]
  TEST_COOL_ENV_VARIABLE = "whazzzzzup"
  FAUNA_GRAPHQL_URL = "https://graphql.us.fauna.com/graphql"

[dev]
  command = "npm run start"
  targetPort = 8888
  port = 8889 # Set Netlify port to differ from Rollup serve
